### ISSUE TITLE
analytics ?

### ISSUE THREAD

**Issue by hollisticated-horse** [syphon-org/landing#17]
Very touchy subject, though there a couple of options that could be okay, if analytics are okay. 

Is it already setup ?

**Comment by ereio** [comment]
I'd prefer to leave analytics off most if not all the web resources we create. Only time I'd be ok with the potential of using analytics would be under any checkout pages for donations or the shop. Currently the landing page is under Cloudflare but that was only for quickly adding TLS. Hope to move away from it soon!
